import { BsFillLightningFill, BsFire } from "react-icons/bs";
import { GiStoneSphere, GiPsychicWaves, GiHighGrass, GiPolarStar, GiPoisonGas, GiAngelWings, GiGhost, GiMetalScales, GiFairyWand   } from "react-icons/gi";
import { FaRegSnowflake } from "react-icons/fa";
import { FaHandBackFist, FaMountainSun, FaBug, FaDragon    } from "react-icons/fa6";
import { CgDarkMode } from "react-icons/cg";
import { IoIosWater } from "react-icons/io"


const colorMap = {
    water: {
        color: '#2389da',
        darkerColor: '#1a6aa8',
        icon: IoIosWater,
        typeChart: {
            bug: 1,
            dark: 1,
            dragon: 1,
            electric: 2,
            fairy: 1,
            fighting: 1,
            fire: 0.5,
            flying: 1,
            ghost: 1,
            grass: 2,
            ground: 1,
            ice: 0.5,
            normal: 1,
            poison: 1,
            psychic: 1,
            rock: 1,
            steel: 0.5,
            water: 0.5
          },
    },
    fire: {
        color: '#ff5a00',
        darkerColor: '#cc4800',
        icon: BsFire,
        typeChart: {
            bug: 0.5,
            dark: 1,
            dragon: 1,
            electric: 1,
            fairy: 0.5,
            fighting: 1,
            fire: 0.5,
            flying: 1,
            ghost: 1,
            grass: 0.5,
            ground: 2,
            ice: 0.5,
            normal: 1,
            poison: 1,
            psychic: 1,
            rock: 2,
            steel: 0.5,
            water: 2
          },
    },
    ice: {
        color: '#368BC1',
        darkerColor: '#2a6e98',
        icon: FaRegSnowflake,
        typeChart: {
            bug: 1,
            dark: 1,
            dragon: 1,
            electric: 1,
            fairy: 1,
            fighting: 2,
            fire: 2,
            flying: 1,
            ghost: 1,
            grass: 1,
            ground: 1,
            ice: 0.5,
            normal: 1,
            poison: 1,
            psychic: 1,
            rock: 2,
            steel: 2,
            water: 1
          },
    },
    psychic: {
        color: '#635c84',
        darkerColor: '#4e4968',
        icon: GiPsychicWaves,
        typeChart: {
            bug: 2,
            dark: 2,
            dragon: 1,
            electric: 1,
            fairy: 1,
            fighting: 0.5,
            fire: 1,
            flying: 1,
            ghost: 2,
            grass: 1,
            ground: 1,
            ice: 1,
            normal: 1,
            poison: 1,
            psychic: 0.5,
            rock: 1,
            steel: 1,
            water: 1
          },
    },
    grass: {
        color: '#40a829',
        darkerColor: '#338620',
        icon: GiHighGrass,
        typeChart: {
            bug: 2,
            dark: 1,
            dragon: 1,
            electric: 0.5,
            fairy: 1,
            fighting: 1,
            fire: 2,
            flying: 2,
            ghost: 1,
            grass: 0.5,
            ground: 0.5,
            ice: 2,
            normal: 1,
            poison: 2,
            psychic: 1,
            rock: 1,
            steel: 1,
            water: 0.5
          },
    },
    normal: {
        color: '#A8A77A',
        darkerColor: '#868659',
        icon: GiPolarStar,
        typeChart: {
            bug: 1,
            dark: 1,
            dragon: 1,
            electric: 1,
            fairy: 1,
            fighting: 2,
            fire: 1,
            flying: 1,
            ghost: 0,
            grass: 1,
            ground: 1,
            ice: 1,
            normal: 1,
            poison: 1,
            psychic: 1,
            rock: 1,
            steel: 1,
            water: 1
          },
    },
    electric: {
        color: '#f7e12c',
        darkerColor: '#c6b222',
        icon: BsFillLightningFill,
        typeChart: {
            bug: 1,
            dark: 1,
            dragon: 1,
            electric: 0.5,
            fairy: 1,
            fighting: 1,
            fire: 1,
            flying: 0.5,
            ghost: 1,
            grass: 1,
            ground: 2,
            ice: 1,
            normal: 1,
            poison: 1,
            psychic: 1,
            rock: 1,
            steel: 0.5,
            water: 1
          },
    },
    fighting: {
        color: '#C22E28',
        darkerColor: '#991e1b',
        icon: FaHandBackFist,
        typeChart: {
            bug: 0.5,
            dark: 0.5,
            dragon: 1,
            electric: 1,
            fairy: 2,
            fighting: 1,
            fire: 1,
            flying: 2,
            ghost: 1,
            grass: 1,
            ground: 1,
            ice: 1,
            normal: 1,
            poison: 1,
            psychic: 2,
            rock: 0.5,
            steel: 1,
            water: 1
          },
    },
    poison: {
        color: '#A33EA1',
        darkerColor: '#822f80',
        icon: GiPoisonGas, 
        typeChart: {
            bug: 0.5,
            dark: 1,
            dragon: 1,
            electric: 1,
            fairy: 0.5,
            fighting: 0.5,
            fire: 1,
            flying: 1,
            ghost: 1,
            grass: 0.5,
            ground: 2,
            ice: 1,
            normal: 1,
            poison: 0.5,
            psychic: 2,
            rock: 1,
            steel: 1,
            water: 1
          },
    },
    rock: {
        color: '#B6A136',
        darkerColor: '#8f802a',
        icon: GiStoneSphere,
        typeChart: {
            bug: 1,
            dark: 1,
            dragon: 1,
            electric: 1,
            fairy: 1,
            fighting: 2,
            fire: 0.5,
            flying: 0.5,
            ghost: 1,
            grass: 2,
            ground: 2,
            ice: 1,
            normal: 0.5,
            poison: 0.5,
            psychic: 1,
            rock: 1,
            steel: 2,
            water: 2
          },
    },
    ground: {
        color: '#E2BF65',
        darkerColor: '#b3974e',
        icon: FaMountainSun ,
        typeChart: {
            bug: 1,
            dark: 1,
            dragon: 1,
            electric: 0,
            fairy: 1,
            fighting: 1,
            fire: 1,
            flying: 1,
            ghost: 1,
            grass: 2,
            ground: 1,
            ice: 2,
            normal: 1,
            poison: 0.5,
            psychic: 1,
            rock: 0.5,
            steel: 1,
            water: 2
          },
    },
    flying: {
        color: '#A98FF3',
        darkerColor: '#8773c2',
        icon: GiAngelWings ,
        typeChart: {
            bug: 0.5,
            dark: 1,
            dragon: 1,
            electric: 2,
            fairy: 1,
            fighting: 0.5,
            fire: 1,
            flying: 1,
            ghost: 1,
            grass: 0.5,
            ground: 0,
            ice: 2,
            normal: 1,
            poison: 1,
            psychic: 1,
            rock: 2,
            steel: 1,
            water: 1
          },
    },
    bug: {
        color: '#A6B91A',
        darkerColor: '#849014',
        icon: FaBug ,
        typeChart: {
            bug: 1,
            dark: 1,
            dragon: 1,
            electric: 1,
            fairy: 1,
            fighting: 0.5,
            fire: 2,
            flying: 2,
            ghost: 1,
            grass: 0.5,
            ground: 0.5,
            ice: 1,
            normal: 1,
            poison: 1,
            psychic: 1,
            rock: 2,
            steel: 1,
            water: 1
          },
    },
    ghost: {
        color: '#735797',
        darkerColor: '#5b4678',
        icon: GiGhost ,
        typeChart: {
            bug: 0.5,
            dark: 2,
            dragon: 1,
            electric: 1,
            fairy: 1,
            fighting: 0,
            fire: 1,
            flying: 1,
            ghost: 2,
            grass: 1,
            ground: 1,
            ice: 1,
            normal: 0,
            poison: 0.5,
            psychic: 1,
            rock: 1,
            steel: 1,
            water: 1
          },
    },
    dragon: {
        color: '#6F35FC',
        darkerColor: '#582abf',
        icon: FaDragon ,
        typeChart: {
            bug: 1,
            dark: 1,
            dragon: 2,
            electric: 0.5,
            fairy: 2,
            fighting: 1,
            fire: 0.5,
            flying: 1,
            ghost: 1,
            grass: 0.5,
            ground: 1,
            ice: 2,
            normal: 1,
            poison: 1,
            psychic: 1,
            rock: 1,
            steel: 1,
            water: 0.5
          },
    },
    dark: {
        color: '#705746',
        darkerColor: '#564336',
        icon: CgDarkMode,
        typeChart: {
            bug: 2,
            dark: 0.5,
            dragon: 1,
            electric: 1,
            fairy: 2,
            fighting: 2,
            fire: 1,
            flying: 1,
            ghost: 0.5,
            grass: 1,
            ground: 1,
            ice: 1,
            normal: 1,
            poison: 1,
            psychic: 0,
            rock: 1,
            steel: 1,
            water: 1
          },
    },
    steel: {
        color: '#B7B7CE',
        darkerColor: '#9292a5',
        icon: GiMetalScales ,
        typeChart: {
            bug: 0.5,
            dark: 1,
            dragon: 0.5,
            electric: 1,
            fairy: 0.5,
            fighting: 2,
            fire: 2,
            flying: 0.5,
            ghost: 1,
            grass: 0.5,
            ground: 2,
            ice: 0.5,
            normal: 0.5,
            poison: 0,
            psychic: 0.5,
            rock: 0.5,
            steel: 0.5,
            water: 1
          },
    },
    fairy: {
        color: '#D685AD',
        darkerColor: '#aa6b8a',
        icon: GiFairyWand , 
        typeChart: {
            bug: 0.5,
            dark: 0.5,
            dragon: 0,
            electric: 1,
            fairy: 1,
            fighting: 0.5,
            fire: 1,
            flying: 1,
            ghost: 1,
            grass: 1,
            ground: 1,
            ice: 1,
            normal: 1,
            poison: 2,
            psychic: 1,
            rock: 1,
            steel: 2,
            water: 1
          },
    },
}



export default colorMap


// give me a darker version of he following: 
// water: #2389da
// fire: #ff5a00
// ice: #368BC1
// psychic #635c84
// grass: #40a829
// normal: #A8A77A
// electric: #f7e12c
//  fighting #C22E28
// Poison: #A33EA1
// rock: #B6A136
// ground : #E2BF65
// flying: #A98FF3
// bug: #A6B91A
// ghost: #735797
// dragon: #6F35FC
// dark: #705746
// steel: #B7B7CE
// fairy: #D685AD